name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install cypress@12.14.0
          npm install -D @shelex/cypress-allure-plugin allure-commandline

      - name: Run Cypress Tests
        run: |
          npx cypress run
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        if: always() # Ensures this step runs even if tests fail
        with:
          name: allure-report
          path: allure-report

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: always() # Ensures this step runs even if tests fail
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: always() # Ensures this step runs even if tests fail
        with:
          name: cypress-videos
          path: cypress/videos
